### ISSUE TITLE
"Open Declaration" is not working

### ISSUE THREAD

**Issue by chunkhopkins** [AgileReview-Project/AgileReview-Legacy-Plugin#16] opened 2015-10-16 15:35 UTC
The Open Declaration (Ctrl + left click) does not work in the C/C++ perspective after install the Agile review tool plugin. Actually this feature is working properly with F3 button, only the Ctrl functionality is corrupted.
This strange behavior can be eliminated when switch to the AgileReview perspective, push the Ctrl button and switch back to the C/C++ perspective. This function will work properly till the next Eclipse start, but this procedure shall perform every Eclipse start.

Used version:
Eclipse IDE for C/C++ Developers
Version: Luna Release (4.4.0)
Build id: 20140612-0600

AgileReview Plug-In 0.9.3.201507021242

**Comment by postmann** [comment] 2015-10-17 17:26
Hi @chunkhopkins, thanks for your feedback. I'll check this issue in the next days.

**Comment by chunkhopkins** [comment] 2015-10-22 11:00
Thank you it's a good news. :)

**Comment by postmann** [comment] 2015-11-14 09:46
It's odd, I cannot reproduce this issue though I'm using Luna as well. I assume that the key-bindings of AR and some other plugin are interfering.

@chunkhopkins: Can you provide more information on you installation or even some demo-project? My C/C++ knowledge is near to non-existent, maybe I missed something when creating my dummy project for testing.

Here's my test project: [Test-Project.zip.txt](https://github.com/AgileReview-Project/AgileReview-Legacy-Plugin/files/34583/Test-Project.zip.txt). Had to add ".txt" in order to cheat GitHub :)

BTW: Are you really using AgileReview 0.9.3.xx? We never released a version higher than 0.9.2.201506201602. Are you using some custom build?

**Comment by postmann** [comment] 2016-02-14 10:49
I even checked with Eclipse for C/C++ Developers. I'm closing this issue as I'm not able to reproduce and no feedback was provided.

**Closed by postmann** 2016-02-14 10:49 UTC
